### ISSUE TITLE
Create form for collecting MP events

### ISSUE THREAD

**Issue by toolness** [mozilla/learning-networks#136]
This issue has been migrated from mozilla/teach.webmaker.org#738.

It was originally written by [hannahkane](https://api.github.com/users/hannahkane) on Mon Apr 20 2015 and had the following description:

> As discussed with stakeholders, we'll be collecting MP data through a google form, rather than through a public-facing events tool. 
> 
> We need to determine what information we want to collect and create the form.
> 
> Here's an example to draw inspiration from: https://www.madewithcode.com/events#add

On Mon Apr 20 2015, [hannahkane](https://api.github.com/users/hannahkane) commented:

> Who should this be assigned to? **@****amirad** ? **@****ldecoursy** ?

On Mon Apr 20 2015, [ldecoursy](https://api.github.com/users/ldecoursy) commented:

> I'll assign myself - here's a draft of fields I think we should include https://teach.etherpad.mozilla.org/eventform
> 
> **@****amirad** **@****chrislarry33** **@****adamlofting** anything here you think we don't need or that's missing?

**Comment by ldecoursy** [comment]
Here's the draft form http://bit.ly/1F4jomG

During a call with @amirad and @thornet today, we talked about a form that is not just for collecting MP-specific info, but something with more longevity that gets us to a better understanding about how people are teaching with our stuff in general. 

Data we collect should still help us test this hypothesis: Maker Parties are a good launchpad for Clubs

Would love thoughts/edits/suggestions @chrislarry33 @hannahkane @adamlofting

**Comment by hannahkane** [comment]
Looks good. Some minor suggestions below. 

I guess I'm a little confused about the idea of collecting non-MP-specific info. In what other contexts will we use this form? 

I like the hypothesis, but now I'm wondering what we mean by that. Do we mean, "Hosting a MP increases the likelihood that someone will host a Club?" (in which case we may want to measure the likelihood before and after), or do we mean, "Hosting a Maker Party makes someone a better Club Leader" (not sure how we'd measure that).

Minor suggestions for the form:
- "Where are you teaching the Web?" question suggests it's a multi-select, but the field values are radio buttons
- We may want to suggest a format or validate the date field, so we're not confused about how people enter their dates
- "How many learners?" questions should be radio buttons, rather than checkboxes
- Age range should stay checkboxes (in case the event is multi-age), but remove "Please select one option" copy
- Should probably add a distinct question for beginner/intermediate/advanced if we care about that data, rather than relying on the respondent to include it in the "What are you teaching?" question
- "Are you interested?" should probably be radio buttons

**Comment by ldecoursy** [comment]
Think we need a way (in time for Maker Party and before the  Directory is ready) for people to "sign up" and for us to collect information from people who may not be ready to add clubs to the map - so we know who and where they are, and can tailor outreach and materials to them.

Re: the hypothesis, we want to see if Maker Party is a good first step/activation to get people to start clubs. We'll need to cross-ref people who fill out the form and select (standalone event) against the list of people who are adding clubs. 

But the information we gather will also help us better understand the contexts within which people are teaching the web, how many people they're reaching, and where there's heat - if we need to recruit RC's to help activate clubs, for instance.

**Comment by chrislarry33** [comment]
I agree with this level of "join us" but I think it needs to be scoped that way 
1) A call to join even if people on quite sure yet what they would do
2) Collection of demographic info we want/need
3) Way they then get into a regular info/update stream
4) Transactional email that offers them  1-3 distinct CTAs that get them participating

We need to develop a relationship with them before we know how/why they are teaching with us

This we need soon, but can also be evergreen. Am I missing something?

**Comment by chrislarry33** [comment]
I agree with this level of "join us" but I think it needs to be scoped that way 
1) A call to join even if people on quite sure yet what they would do
2) Collection of demographic info we want/need
3) Way they then get into a regular info/update stream
4) Transactional email that offers them  1-3 distinct CTAs that get them participating

We need to develop a relationship with them before we know how/why they are teaching with us

This we need soon, but can also be evergreen. Am I missing something?

**Comment by chrislarry33** [comment]
I agree with this level of "join us" but I think it needs to be scoped that way 
1) A call to join even if people on quite sure yet what they would do
2) Collection of demographic info we want/need
3) Way they then get into a regular info/update stream
4) Transactional email that offers them  1-3 distinct CTAs that get them participating

We need to develop a relationship with them before we know how/why they are teaching with us

This we need soon, but can also be evergreen. Am I missing something?

**Comment by hannahkane** [comment]
Can we keep this ticket limited to tracking MP, and open a new ticket for a generic sign-up?

**Comment by amirad** [comment]
Sure.
+1 to this being the hypothesis "Hosting a MP increases the likelihood that someone will host a Club?"
I think when we say longevity we mean make the form applicable to those who sign up events all year around. We need to prepare the form for that.

**Comment by hannahkane** [comment]
I feel like we're conflating two different things.

1) Capturing 2015 Maker Party campaign data and testing the hypothesis that hosting a MP (any time of year) increases the likelihood of starting a Club.

This form is not specific to hosting a Maker Party, so I don't think it serves the goal of proving a causal relationship between hosting a MP and starting a Club. The standalone option reads, "for example, a one day workshop, hackathon, or Maker Party". If someone checks that box and later creates a club, we won't know if they'd previously hosted a MP, a one day workshop, or a hackathon. Regarding the question of using it year round—I saw an earlier version of this form that was specific to hosting MP events. I don't see why that form couldn't be used year round. Having a MP-specific form would also allow us to gather the data needed to tell the story of the two-week MP campaign (i.e. have an infographic). 

2) Gathering data about the current practices and interests of our audience.

It sounds like we also want to gather information about either our site visitors or members of our community broadly, in order to tailor our outreach and materials to them. I can't tell if we mean to apply this information to individual people (e.g. sending someone an email that says, "You said you're interested in accessing a digital literacy curriculum for 14-24 year-olds in a classroom setting—here you go!"), or in the aggregate (e.g. 60% of survey respondents said they're interested in accessing digital literacy curriculum, so we should make the curriculum more prominent on the site). I'd like to better understand how we'd use the data, in order to determine the best place to put this form. If we're interested in the aggregate, we could send this as a one-time survey to our lists, or perhaps include a link to it in the Welcome email. If we're planning to customize the experience for individuals based on their specific responses, I'd like to talk through what that looks like.

**Comment by adamlofting** [comment]
I'm just catching up after PTO, but agree with Hannah's questions wrt to the scope of this ticket. 

The draft form linked above looks like a good general 'join us' form. I can see us using that a lot on the site.

But I think there is also a need for a specific 'tell us about your maker party' form. This can be even simpler: Name, email, date of MP, any other fields we want. This will give us a record of how many events happened during MP and allow us to prove or disprove the hypothesis wrt MP/clubs.

Both forms are useful, maybe we just need to split this into to two tickets?

**Comment by ldecoursy** [comment]
Per latest metrics plan of record http://etherpad.io/metrics, we will not be specifically counting the # and details of Maker Party events. Closing this ticket and will re-post the link to the draft survey (as part of the new pledge/user flow in relevant tickets).
