### ISSUE TITLE
Template an Etherpad and Discourse thread for Coordinating Clubs

### ISSUE THREAD

**Issue by toolness** [mozilla/learning-networks#159]
This issue has been migrated from mozilla/teach.webmaker.org#802.

It was originally written by [LauraHilliger](https://api.github.com/users/LauraHilliger) on Thu Apr 23 2015 and had the following description:

> In the Open Tools module, we need actions around:
> - Protocols & patterns for coordinating clubs
> - How to connect with RCs and regions (video bridge / cross-region comms & connection)
> 
> My idea would be to set up a template etherpad and discourse thread that shows how online coordination might look like. Then the actions in mozilla/teach.webmaker.org#753 would be to copy/paste/create.
> 
> **@****soapdog** how are you coordinating your club captains in an online environment? Do you have some things we could pull from?

On Thu Apr 23 2015, [soapdog](https://api.github.com/users/soapdog) commented:

> **@****LauraHilliger** its early days, we're yet to have club captains. Right now we're playing all roles. My main idea for our Rio project is to have the following things:
> - private mailing list for LAN House owners and project stakeholders and captains. This list will be used to logistics.
> - public mailing list for everyone including all members of above list plus learners and interested parties. This is our discussion list. Mailing list is low attrition and doesn't require its members to learn something new. I don't know if discourse is fully localized into Portuguese and we can't use webapps in English in our context.
> - Bilingual blog about the project where all posts are duplicated in English and Portuguese. This could be a simple site about the project. Need to ask the infrastructure folks for a place to host it.
> - Planet page on our site. We want each LAN House (aka cybercafes) to maintain their own blog and we plan to aggregate them in a planet.
> 
> I was waiting for my contract and my LDAP account to pursuit these. Now that things are settled, I will figure out how to ask about these things.

On Thu Apr 23 2015, [chrislarry33](https://api.github.com/users/chrislarry33) commented:

> **@****soapdog** This looks like a strong plan to get going and gain momentum. Glad you have your LDAP so you can start to move quickly. Looking forward to seeing how this progresses,  important work for our team. 

On Fri Apr 24 2015, [LauraHilliger](https://api.github.com/users/LauraHilliger) commented:

> **@****soapdog** on the localization + Discourse question, it appears that the software is, indeed, fully localized into Portuguese. https://www.transifex.com/projects/p/discourse-org/
> 
> We'll need to investigate from the tech perspective how we accomplish this, therefore I've filed https://github.com/MozillaFoundation/plan/issues/440

**Comment by thornet** [comment]
@LauraHilliger @soapdog let's review the Rio workflow and see how it layers into "Your 1st Month as an RC (#143). Think we need to balance i) ease of use and momentum with ii) ability to connect systematically with your club captains. 

At the moment, we removed blogs from the RC workflow and instead encourage posting on Discourse. This reduces the amount of extra sites to keep track of. 

Maybe we need to add "set up mailing lists" to the RC guide, since it's not in there yet. 

Thoughts?

**Comment by toolness** [comment]
Woooooo, I'm happy to see the migrated tickets being used :grin:

**Comment by LauraHilliger** [comment]
I guess it's important to consider what info we put in the RC guide vs what we put in attached TLM modules. Instead of adding Mailing Lists to the RC guide (b/c if we add mailing lists, I would argue for adding an online presence), maybe we should add Mailing Lists to the "Reflecting Openly" TLM module. The module is already detailing further what is in the RC Guide, so maybe that's a better place for more built out information.

Current Reflecting Openly is here (I've noted Mailing lists, but not added much content around it). Feel free to comment in the doc too! 

https://docs.google.com/document/d/1ZYAsSM858SK_Pljo-jpwEzL4uuOE-jTcMfHmwuex_Ag/edit#

**Comment by LauraHilliger** [comment]
We have Stories "templated" and the RC & CC guides + TLM will determine if we need to template a "call" etherpad. Closing for now. 

http://discourse.webmaker.org/category/clubs/stories
