### ISSUE TITLE
Finalize and ship Maker Party partners kit

### ISSUE THREAD

**Issue by KevZawacki** [mozilla/learning-networks#179]
Maker Party 2015 partners kit is available for review here: https://docs.google.com/document/d/1O7BJf63vPjNLLV8GWXB_xs2ZF7IdPnAMm4uktEGKHMc/edit

We'll link to it when we email past partners (https://party.webmaker.org/en-US/partners) about participating this year.

@amirad @HPaulJohnson @ldecoursy

**Comment by ldecoursy** [comment]
This is pretty awesome, thanks @KevZawacki! 

Do we need something up top to provide context about what Maker Party "partnership" looks like this year?

**Comment by KevZawacki** [comment]
Good idea! I've just added language to the start of the doc.

**Comment by amirad** [comment]
@KevZawacki @HPaulJohnson I DID IT! I edited. Main thing to note is that I took out specific 'partner' wording mainly because we will send this to partners/orgs to share but we don't want to handle the specifics around people calling themselves partners. 

I will include this in my email to past participating orgs in the next 1-2 weeks
