### ISSUE TITLE
Create spreadsheet for tracking RCs and clubs

### ISSUE THREAD

**Issue by thornet** [mozilla/learning-networks#181]
We need a big, shared spreadsheet for: 
- Staff organizers to record their relationship to and progress of their RCs
- RCs to record their relationship to and progress of their club captains
- Staff and RCs to see club captains that applied via the website and are not yet assigned. 

We'll demo this on Tues, June 2 in the next RC call. 

Ideally, we can have the data update a visualization like this: http://thornet.github.io/radial-tree/ (but that's a later ticket). 

cc @ldecoursy @adamlofting @hannahkane

**Comment by ldecoursy** [comment]
I think the first two are doable in a Google spreadsheet, whereas the last seems like something we might need to export from the site admin. I have time blocked tomorrow am to draft something.

**Comment by thornet** [comment]
+1. Let's aim for the first two items and work with others to get the export right.

**Comment by hannahkane** [comment]
Can we do the third bullet point manually for awhile? Until it becomes unwieldy (or just before :))?

**Comment by adamlofting** [comment]
I just want to add a note to this for the long term thinking. :smile: 

That description of a `Big, shared spreadsheet that ...` is a description of a typical 'CRM system'. Don't worry yet about what that means in terms of software, because it's good to start with a spreadsheet and progressively learn about what fields you need and what you don't. 

But over time I can work with you to think about what software can help make this manageable when there are 5,000 clubs.

**Comment by thornet** [comment]
This is done! Central Station, choo choo choo.
