### ISSUE TITLE
Add "Assessment tips" to curriculum activities

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/learning-networks#183]
@omnignorant and I discussed adding examples of what "done" looks like to help educators assess learning. We discussed 4 states of examples, but I would limit to:
- incomplete
- meets
- exceptional

We can use this ticket to formulate what an example contains (e.g. image + wording) starting with the Web Literacy Basics module.

**Comment by jgmac1106** [comment]
There was a discussion @thornet started on rethinking assessment over at discourse and we played with some interesting ways to assess learning.

My big questions would be if badges are driving the assessment and if club captains, like mentors under old model, would be issuer. If so the incomplete, meets, exceptional might be based on the badge criterion.

This would mean will the badges have just a binary state (issued or denied)? or if we use a three point holistic rubric and you want exemplars it might be easier until we have more finished products from the Clubs to choose from rather than trying to create them ourselves.

**Comment by amirad** [comment]
@chadsansing can you review this ticket and either keep it in your scope of work or close it?

**Comment by chadsansing** [comment]
Closing. Blocked pending badges relaunch.
