### ISSUE TITLE
Write interview script for RCs to vet incoming clubs

### ISSUE THREAD

**Issue by thornet** [mozilla/learning-networks#193]
cc @amirad 

Let's write 3-5 questions so RCs can properly vet interested clubs coming in from the website. 

This should also include a plan for where to store the results of those interview conversations.

**Comment by amirad** [comment]
Can we make a google doc that they fill out with interviewer name, interviewee name and questions? That way it sorts it and we have access to organized info. 
I think questions have two paths for new adds based on whether they are running an existing club/program or if they are doing new one.

Path 1 - New club
• When are you starting your new?
• How will you recruit learners? mentors?
• Where will your club take place? How often? Have you booked the first few dates?
• What curriculum are you wanting to teach in your club?

Path 2 - Existing club/program
• How often do you currently meet with your learners? 
• Can you share more info about your learners.
• What have you done in the past? What do you want to do?
• What types of resources do you need to help your club?

**Comment by thornet** [comment]
cc @soapdog who said he'd be interested to review and/or write the interview scripts. 

@amirad think the questions you have are good data points, but think we'll need some more emotional/motivational ones, like "what does web literacy mean to you?" "which communities do you serve and why?" 

Drafting: https://teach.etherpad.mozilla.org/clubs-interview

**Comment by thornet** [comment]
from @soapdog, how the Reps do it: https://wiki.mozilla.org/ReMo/SOPs/Mentoring/Screening#Step_3:_Interviewing_the_applicant

**Comment by thornet** [comment]
- make a decision for if/how the interview data is retained. An assumption is that we want some notes from the interviewer at the least.

**Comment by soapdog** [comment]
Our idea is to keep the interview short and informal, this is not a bank loan interview but the beginning of an partnership based on the common goal of universal web literacy. Instead of following the questions below like a script written in stone you should adapt and rephrase the questions to suit your own style. The idea is to make sure all topics below are covered.
- Can you tell us a bit more about your story and how you became involved with Mozilla?
- Why do you think universal web literacy is a worthy goal? (or why should we teach the web?)
- Can you tell us one story about how the Web impacted your life?
- What kind of stories or transformations you'd like to achieve in this program?
- Why do you want to start a Mozilla Club?
- What could you do with the Mozilla Club that you could not achieve before?
- Can you tell us more about the club you plan to start such as where it will meet, what kind of participant you hope to attract to it?
- How are you going to recruit members for the club? what about volunteers for session facilitation?
- Can you run a recurring group and meet at least three times?
- What kind of curriculum you would like to have available for you?
- What kind of support to you expect from Mozilla?
- How could we make your club more awesome? (this is a moonshot question)
- Imagine your club is running for three years already, what kind of stories you would like to have to tell others? What is your dream story about the club?
- What steps you would need to take to make that story a reality?

This set of questions should give us an impression about our potential CC, their aspirations and dreams and if they can commit to run a club. I would love to have feedback from you all regarding this set of questions.

**Comment by thornet** [comment]
@soapdog: this is great, thanks! 

Do you have a suggestion for where and how the RCs should log notes from their interviews? A Google Form that auto-populates a tab in Central Station, maybe? And also where we should post the interview questions for easy access for the RCs?

My remix of your q's, aiming for max. 10: 
- Can you tell us about **your own journey:** what's your relationship to the web? how you came to care about web literacy today? 
- What kind of **success stories or transformations would you like to enable** with your club? what does that look like in the next month? in the next year?
- **Why do you want to host a Mozilla Club?** what will you be able achieve with your club that you could not do before?
- Can you tell us more about **how you'll organize your club?** i.e. where it will meet, what kind of participant you want to serve?
- What **steps you will need to take** to make that story a reality?
- What kind of **curriculum you would like to have available** for you?
- **How can we support you** in making your club more effective and fun?
- **How are you going to recruit members for the club?** what about volunteers to mentor and facilitate session with you?
- **Will you host a local group of learners that meets at least three times in the next 6 months to explore how to read, write and participate with the web in an engaging and inclusive way?**

**Comment by soapdog** [comment]
Perfect Remix! :+1: 

The idea of a form that auto-populate central station is also great but I have no idea how to build such form, my google-docs-fu is not as strong as yours.

I would like to see that form being more like a free-form input than multiple choice links. We could have the following inputs:
- one multiple choice link with options "ACCEPTED", "REJECTED" or some other more clever wordsmithing to flag if the persons is joining the program or not
- What type of club and stories they want to generate.
- More info about their journey

**Comment by amirad** [comment]
+1 to open verbatim answers. Maybe this can just be a separate google survey that RC's fill out and submit? 

I like the questions the remixed questions Michelle submitted. Maybe add one that looks at "what are the challenges to teaching the web in your area" similar to how we ask RCs.

**Comment by anmechung** [comment]
Agree with Amira.  In keeping with your limit of ten, #8 can be remixed:
What challenges do you foresee in starting, sustaining, and making your club more effective?  What kind of support might you need to overcome your challenges?

**Comment by anmechung** [comment]
Also, will you be collecting periodic feedback on progress and process with the RCs? Goal of this is for continuous improvement.  i.e. including understanding what is an ideal frequency for particular audiences.

**Comment by anmechung** [comment]
... and what might be cultural differences in running clubs in one country vs another, or one group vs another.

**Comment by soapdog** [comment]
Can we have a separate spreadsheet for the interview answers? I have some ideas about the form but it may require a bit of scripting and I am afraid of doing something wrong with central station.

**Comment by chrislarry33** [comment]
"not a bank loan"....classic and correct

Any way these can be done openly and/or end up as content?

**Comment by hannahkane** [comment]
Taking this out of the July 10th milestone, so we can close the milestone. Feel free to add a different milestone.

**Comment by soapdog** [comment]
Can we agree that the hacked version is final and good and update #200 ?

**Comment by thornet** [comment]
@soapdog is making a quick Google Form for this.

**Comment by soapdog** [comment]
Live form at: https://docs.google.com/a/andregarzia.com/forms/d/1S17vlviIVOhgQBmFEXmQ4T94e273aVkTH_w3dp71QgQ/viewform

Form for editing: https://docs.google.com/a/mozilla.com/forms/d/1S17vlviIVOhgQBmFEXmQ4T94e273aVkTH_w3dp71QgQ/edit?usp=sharing

Can I get some feedback on this before updating the doc with a link to the live form?

**Comment by amirad** [comment]
Quick thoughts @soapdog:
•Do we need the RC email address?
•Should we include some info on questions to ask in the form? We don't need open verbatim responses included as well but it would be good to have a short script there
•Should we include why they were or were not accepted into the program?

**Comment by soapdog** [comment]
@amirad :
- Removed the RC email address field.
- Added field for reasoning about the acceptance or refusal into the program
- As for questions to ask, could you elaborate a bit on them plz?

**Comment by amirad** [comment]
The questions an RC would ask the CC when talking on the phone interview. Just a brief guideline of what to talk about.

**Comment by thornet** [comment]
Thanks, @soapdog! This looks great. A small edit: could we make that one field be "Do you recommend that this Mozilla Club is accepted into the program?" YES/NO/UNSURE, REQUESTING STAFF REVIEW

**Comment by thornet** [comment]
I made the edits directly to the form. Closing!
