### ISSUE TITLE
Testing on Expanded Privacy Curriculum

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#246]
Looking for bugs, edits, and suggested revisions for clarity, nav, & sequencing. Also, original material mixed 2nd and 3rd person, so sometimes this feels flipped and often this feels like a self-guided module. What are your reactions to that?

Here is [the project](http://chadsansing.github.io/curriculum-testing/expanded-privacy-curriculum/). The index is just a place-holder for the /activities landing page to be developed.

Here is the [/activities page content doc](https://docs.google.com/a/mozilla.com/document/d/1Gr9PhZQhKQTFfShW8-rMWvqJz11W6i8rWCuwPs5_dWQ/edit?usp=sharing).

cc @chrislarry33, @ldecoursy, @amirad, @omnignorant, @leahatplay, @hannahkane - pls cc & share widely.

[Back to issues.](https://github.com/mozilla/learning-networks/issues/)

**Comment by chadsansing** [comment]
Added buttons to the next activity at the bottom of each page.

**Comment by amirad** [comment]
Data retention is missing some times!

**Comment by chadsansing** [comment]
Thanks, @amirad! Added total time and Minding Your Metadata time.

**Comment by amirad** [comment]
Np!

@soapdog @jvallera - new privacy curriculum if you have time to take a peek and give feedback

**Comment by jvallera** [comment]
@chadsansing link broken/not working on Privacy section here: "You're Leaving Footprints - Review Questions"

**Comment by chadsansing** [comment]
@jvallera, many thanks. Fixed.

**Comment by KGorr** [comment]
Overall comment: Is there a way to get the links to videos and such to open in a different tab. It disconnected me from the learning, as a participant, when I had to go back and forth in one tab.

Comments on the Privacy Kit:
Under the "If it's personal offline, it's personal online" > "Privacy on the street" description:
-There is an extra "the" under the Privacy on the street description: "of its the terms and conditions."
- There is a typo: possible conseuences 

The "See community remixes" link goes straight to discourse instead of a specific thread. If I've never been on Discourse before, I wouldn't know where to go or what to look for given the specific paragraph CTA.

Under the "Spectrogram for Understansing Privacy" [NOTE typo in the header]:
-there is also a typo in the intro paragraph: "between guadring information." 
- there is a typo in the description, under the bulleted list: "Next, place post itswith the numbers one" 

Under "Privacy Agenda" > Agenda item # 7 - the online EXIF Data finder link isn't working

Under "Tracking Cookies with Lightbeam"
- The lightbeam video isn't playing correctly and links to popcorn maker
- Typo Under Reflect questions: "Why should or why shouldn't everyone should have the tools to investigate who collects data on them? "
- The entire kit says audience is 13+, but this activity says 16+

Under "What's your elevator speech"
- A couple of typos in the description sentence of the page: "Draft and deliver own 30- to 60-second elevator speeches championing helthy data privacy habits online, learning about privacy."
- Under "drafting the speech", a couple of typos in this sentence: "compose your speech online as an something like an audio recording or selide deck" and this one "Try to craft a crips, 30-60 second message"
- There is an extra " after this quote: “The end of privacy is the end of second chances.” - Larry Ponemon"
- Under "rehearse and share", a couple of typos in this sentence: "Share your speech whennever you have the chance to teach pthers how to safely participate on the Web!"
- In the Learning objectives section, typo in this bullet: "Draft a persuasive presentation to connvince others to adopt similar viewpoints on privacy and online privacy habits."

**Comment by KGorr** [comment]
Comments on the Passwords Kit:

Under "Testing Password Strength"
- Under "Reflect on Weak Password Habits"
  - There doesn't seem to be a lot of meat in the curriculum to truly provide the participant (or instructor) with the correct answers. What if they think that using a book quote is a good idea? Where/How are they being guided to get the correct answers, other than a list of bad passwords? Or maybe they know it's not a good idea, but don't really know why - there isn't anything to provide background in that area.
  - Under "Create Bad Password Collage" - it would be helpful to have a call to action here "Share this with you friends to help generate awareness of bad passwords." or something like that.

Under "Creating Strong Passwords" > "Create a passphrase" - Link to Diceware so that participants can do what is being described. Right now, only a list is linked and there is no navigation to get out of it.

Under both the Create a pronounceable and random passwords sections, the linked to password generator does not have the options for exactly what the instructions are asking. The verbiage just needs tweaked to be more clear.

Under "Avoiding Password Reuse"> "Third Party Password Management" 
- typo in first sentence "Reaearch how you can save your passwords" 
- This sentence is'nt really true: "The tradeoff is that you loose the convenience of having the browser auto-fill your passwords." I use lastpass and it auto-populates passwords, even allowing me to choose which account I want to log in with right from the field.
  General comment for this entire page (Avoiding Password Reuse) - the questions should all be bulleted instead of in paragraph form to match your other activity pages.

Under "Two-Factor Authentication"
- Intro typo: "another layer of ssecurity" and also two-factor isn't hyphenated in one place in that paragraph
- Under "avoiding man in the middle attacks" typo - "One simple way to fight man-in-the-middle attackes" and also "and it used Web technologies" [should be "uses" I believe"
- Under "determining if ... works for you" typo: "auenthication" in third Q and also, very last question, it uses HTTPS all caps for the 1st time and also includes tips for the first time.

**Comment by chadsansing** [comment]
@KGorr, you are a feedback star. Keep the edits & suggestions coming.

**Comment by KGorr** [comment]
Comments on Data Retention:

-Learning Objectives has typo in first bullet
-Introduction typos: "and how what should we keep in mind" & "data retnetion"

Under "Pros and Cons of Data Retention"
- Intro typo: "This kinds of data"
- Under "consider the cons": 3rd & 4th bullets both have typos/incorrect wordings
- Under "form an opinion" 3rd bullet is missing the bullet

Under "Follow Your Data Trail"
- Intro typo: "something as simple as your where you go reveals about you"
- Under "reflect on your...trail": typo in next to last paragraph: "an automatic license plate readers" &  last paragraph "metadata bout you" and also: "Whay should people know"

Under "Minding Your Metadata"
- Under "Who does your phone...: typo "outbound callsyou made" and "durationof each call." and "sharethis information"
- "Under "looking into the data" typo: "After five minites" and "Who, besies you"
- Under "reflect on metadata" typo: "collect informatio about?"

**Comment by KGorr** [comment]
@chadsansing I was/am a curriculum developer in my past/"outside Mozilla" life, so I'm happy to help!

**Comment by chadsansing** [comment]
In production.
