### ISSUE TITLE
Complete Case Study for Mozilla Club Rio

### ISSUE THREAD

**Issue by amirad** [mozilla/learning-networks#268]
Do an in-dept case study on Mozilla club Rio 

cc: @Carotejada @soapdog (think we can complete this by end of month?)

**Comment by Carotejada** [comment]
Good to have a Github for this exciting case. Here is the template I sent you https://docs.google.com/a/mozilla.com/spreadsheets/d/1tas859MoTJdVtayMVGxXIWEgL5685HAg8mJ7HlnMZjU/edit?usp=sharing 
@soapdog @amirad

**Comment by amirad** [comment]
Ops that might be the wrong link @Carotejada - that looks like your on-boarding doc?

**Comment by Carotejada** [comment]
:( yes https://docs.google.com/a/mozilla.com/spreadsheets/d/1tas859MoTJdVtayMVGxXIWEgL5685HAg8mJ7HlnMZjU/edit?usp=sharing @amirad @soapdog

**Comment by amirad** [comment]
Much more sense now! It looks beautifulllllllll! We should review deadlines and specifics in our next team call.

**Comment by Carotejada** [comment]
Hey @soapdog!!! How is this awesome case study going? When can we have the info?

**Comment by soapdog** [comment]
Started editing the document, some info is already there. I am also going to have a meeting this week with an A/V crew that will document some of our sessions. The rest of the master plan is also being prepared.

**Comment by amirad** [comment]
@Carotejada to finish this week and then we shift over to a github page. 
Latest copy of report here https://iteachtheweb.wordpress.com/2015/11/25/case-study/

**Comment by Carotejada** [comment]
Report On Air
![on-air](https://cloud.githubusercontent.com/assets/14875631/12328835/415cd936-baab-11e5-87d2-cc82a86c781c.png)

https://iteachtheweb.wordpress.com/2015/11/25/case-study/

**Comment by amirad** [comment]
How do we feel about thimble-afying it @Carotejada?

**Comment by soapdog** [comment]
# Rio Mozilla Club Report 2014-2015 (*structure*) #

## Introduction
andregarzia's note: What is this report about. Why it exists. Why it is important  

## Brazil, The Web & The Economic Crisis
How the economic changes affected the LAN House business? What about the pressure from Zero Rating and similar carrier subsidies? In this section we expand on what changed since 2014 and it affected the LAN House business.  

## What We Set Out To Do
The transition from an appmaker based project into a web literacy project and then leadership development. The creation of the world wide Mozilla Clubs program. How we adapted the program to the Rio context. List the objectives 

## What we did and what happened 
What happened, what activitiies did we do, how often where sessions. Insert Rio case case 

## How The Venues Changed
What happened to the venues originally visited by our team? How  their users changed after our initial report?  

Even though we'll focus on the participating LAN Houses we need  to explain what happened to the other LAN Houses as well. At least what  happened to the other LAN Houses that were recommended by the initial  report (1 closed down, 1 never answered back, 1 had personal/private  health problems and decided not to pursue the project)  

We'll interview LAN House owners, employees and clients again. As  a new section, we'll interview our staff and volunteers.  

## What We Learned
Explain what we learned during this year. What didn't work, what worked well and from that what lessons we took. Its important to highlight what worked well and how we adapted our work to the reality of our venues and public. We came into the project with some per-conceptions on how it should work and some of them were not true.  What worked, what didn't 

## Recommendations
- All based on what we've learned
- Legal Presence  
- Diversity programs  
- More people/staff (internships, fellowship, paid facilitators)  
- No exclusivity to LAN Houses, be able to seed clubs and/or events in venues from different nature such as museums, libraries.  
- Activities focused on engaging and sustaining volunteers as well.  
- Potentially expand into two new states (or large cities) (potentially São Paulo and one from the Northeast)  
 
## Summary

## Acknowledgements

**Comment by Carotejada** [comment]
Good! Will do it by tomorrow.

**Comment by Carotejada** [comment]
Ready! https://d157rqmxrxj6ey.cloudfront.net/carot/24643/

**Comment by amirad** [comment]
Looks SO GOOD!

**Comment by jgmac1106** [comment]
This is awesome,  and a Thimble version for remix will be great for clubs.

**Comment by Carotejada** [comment]
Thank you @jgmac1106

**Comment by soapdog** [comment]
:smile_cat: just to comment again that this is awesome! :smiley_cat:

**Comment by ldecoursy** [comment]
Awesome work! Closing this ticket.
