### ISSUE TITLE
Templates for Profile cards - MozFest

### ISSUE THREAD

**Issue by Carotejada** [mozilla/learning-networks#276]
These are two samples of printed cards that people will customize and hang on wall in the MozFest's opening meet-up. 

The idea is to use strings or arrows to connect people's cards around their contributions to the open web, as leaders.

https://drive.google.com/file/d/0BxN5635WjvALNUM2OGlJd2xrLW8/view?usp=sharing

cc: @omnignorant @jvallera @LindseyFrost @amirad

**Comment by LindseyFrost** [comment]
I think the half-sheet size will be hard to see possibly?  @omnignorant, what do you think about also leaving a space for people to list sessions attended?

I was thinking 4 sections: 

1) I cam here from... (already on draft)
2) I came here to... (already on draft)
3) By the end of the weekend, I'll have developed as a leader by...  (a place to state their goal)
4) Here's my path to get there (a place to plot their path for the weekend)

Maybe 2 and 3 are redundant and could be combined into just #3?

**Comment by jvallera** [comment]
Thanks Carolina! These look great!
….we have less than a week to print so I think we could simplify even more…..I like what @LindseyFrost  suggested, could be shorter maybe...here is what I am thinking:
(Design suggestions: take off the line about the web on the bottom - take out the icons on the upper right....they are cute, but we need as much space as possible for writing - make the left and right areas even in width)

Left section (the "I am" section):
I am...
1. from:
2. here to:

Right section (Pathway section):
This weekend ...
3. My goal is to__________ and I will make this happen by ____________________.

**Comment by LindseyFrost** [comment]
Julia, love these suggestions!

**Comment by ldecoursy** [comment]
+1

**Comment by chrislarry33** [comment]
Let's roll with @jvallera edits on @carotejada design (sub Joey Ramone for Thom Yorke)

**Comment by omnignorant** [comment]
AWSM. Thanks for making the GitHub issue @Carotejada 

+1 to @jvallera brevity and madlib, but @Carotejada @chrislarry33 I'd like to keep @LindseyFrost's original comments in play: 
- Let's make these full-page size;
- Let's leave a space to "plot their pathway" by noting sessions they attended/plan to attend, etc. (could be along the bottom)
- the space for photo/avatar/profile should be left blank in final draft so that people can hand-draw if we have Polaroid problems;
- Can we keep the leadership-dev spirit alive? The "here to" and "my goal is to" are a little repetitive. Perhaps "My goal as a leader is _____________ and I will make this happen by __________________"

If we keep full-pages, there should be room for that. Goal here is to encourage people to record their MozFest stories without being to heavy-handed about it. The badges crew (Digital Me peeps) are doing something similar (inspired by us last year) and we can integrate the two approaches.

I can get them printed overnight here in Chicago, there's no rush for that as long as these are ready by Friday as planned.

**Comment by Carotejada** [comment]
Thank you all for these comments. Thom's picture is because I <3 him and to let us see how it is going to be at the end, but certainly it will be blank in the in final draft and printed templates. 

@LindseyFrost @omnignorant @chrislarry33 @jullia

**Comment by leahatplay** [comment]
Love this mock-up.
 IMO HOW and WHAT you plan to do/develop as a leader post-MozFest is more important than WHEN.  Leaving a space to plot the pathway and then describe how you'll further what you started in profile makes sense  for brevity and Mablib

**Comment by Carotejada** [comment]
Hi! This draft includes almost all the suggestions. I agree with Robert on keeping the leadership-dev spirit alive :dancer: :dart:  

[MOZFEST_Cards.pdf](https://github.com/mozilla/learning-networks/files/21749/MOZFEST_Cards.pdf)

**Comment by chadsansing** [comment]
I am so going to hack these into the MozFest LARP. ;)

**Comment by omnignorant** [comment]
This is looking great! @Carotejada lets freeze this version for feedback on tomorrow's team call and then finalize for Friday. The only item I would edit is to replace "from" with "local to" but let's not do that until tomorrow.

Also, to see how this fits, you can consult the draft rundown for opening meetup here: https://public.etherpad-mozilla.org/p/teach.mozfest2015-opening-meetup

@chadsansing what is a LARP?

**Comment by chadsansing** [comment]
Live Action Role Playing game. A long-standing dream of mine at the Fest - who would you be as a champion of the Open Web character as opportunity to become that person.

**Comment by omnignorant** [comment]
OK, @chadsansing let's do it this year! As long as we have room on the board, there's no reason people be limited to only one persona card, or polaroids for that matter (vs. sketches/doodles). We can give people the option of creating a 2nd "alternate persona" or something? You'll have to model this for us ;)

**Comment by chadsansing** [comment]
Sweet. I will look for my old write-up, as well :) Yeehaw.

**Comment by jvallera** [comment]
super @Carotejada !! Agree w @omnignorant on changing "from" to "local to" also might want to change "here to" to "at Mozfest to"...just to clarify what we want them to respond with.

"My Goal as a leader for web literacy" still seems confusing to me. Many people don't identify as leaders, nevermind leaders of web literacy, so i worry that people will not know how to respond. Lets open this on the call to see what everyone thinks.

**Comment by omnignorant** [comment]
Just jotting down some quick notes:
- [x] replace "from" with "local to"
- [x] replace "here to" with "at MozFest to"
- [x] replace "My goal as a leader..." with "What leadership means to me."
- [x] replace "and I would make this happen..." with "Sessions where you can find me:" numbered list
- [x] scratch "Sessions I plan to attend" section
- [x] make all fields "in five words or less"
- [x] add "connections" prompting along the border for taping string to
- [x] create [example poster](https://photos.google.com/share/AF1QipN_5nX82wEhDqGB-SMMuk_RvnAA9eietwTnPN6fTrG3BV_HHCbNFFSWTeKK23ESBA/photo/AF1QipNFJ1VwJiFfKaP2H1S-NaU1OJ5oxgs0fWVLZ2fD?key=QUZGRGFWQVBMV0x0WmVUcUs4N1V6b2gtSFVNYVVn) of what the leaderboard should look like when finished
- [x] create example persona cards w/ Thom Yorke or hand-drawing

Instead of icons representing connections, we're going to use colored yarn. 

| Color | Connection |
| --- | --- |
| Red | Sessions |
| Blue | Skills |
| Green | Makes |
| Purple | Interests |
| Yellow | Inspiration |

@LindseyFrost we'll need to add multi-colored string/yarn to the supply list or make a trip to Michael's. Which is more advisable at this stage?

**Comment by Carotejada** [comment]
Hi everyone! we made some changes in the last minute trying to make it more simple...
[MOZFEST_Cards_V2.pdf](https://github.com/mozilla/learning-networks/files/23783/MOZFEST_Cards_V2.pdf)
[MOZFEST_Cards_V1.pdf](https://github.com/mozilla/learning-networks/files/23787/MOZFEST_Cards_V1.pdf)

What do you think?

**Comment by LindseyFrost** [comment]
Can someone other than me submit this to the supply form today? I am at
conference that inexplicably has no WiFi.

LF

**Comment by omnignorant** [comment]
@LindseyFrost sounds like the worst conference ever! What's the point of a conference if you can't do work during the talks? Which is also why MozFest is the best conference ever: there is only work and no talk! I'll complete the supply form for you (though, I've lost track of where that lives...)

@Carotejada you are amazing. I think we should absolutely go with V2. It's focused and visually clean/appealing. It also makes the connections part simple, simple, simple. 

It's missing the "what does leadership mean to you?" prompt though. We could just make that conversational... or what if we made that central poster read "What does leadership mean to you?" and let our folks write answers with markers or post-its???

One other tweak before we send to the printer! Can you please color-code the circles to match the string-legend?
