### ISSUE TITLE
Need testing on Web Lit Basics II page content document

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#278]
Please test [this page](https://docs.google.com/document/d/1TK2AAc5Bhe0sO1plj_ZtfI7LIMoc7rHnzmHoTt_URMI/edit?usp=sharing) for
- Broken links.
- Copy edits.
- Appropriate sequencing of activities.

Feedback & insights welcome. 

Please continue testing the activities and associated Thimble projects and tutorials for the same.

[Back to issues](https://github.com/mozilla/learning-networks/issues)

**Comment by hannahkane** [comment]
Read through the first four activities, and left really basic feedback (typos). 

Just a process point: it might be easier to give this kind of feedback earlier in the process, when the content is in a Google doc, for example.

**Comment by chadsansing** [comment]
I like it. I usually begin in TextMate and then migrate to GitHub, but can add a content step if that is better practice. Will level up the proof-reading ahead of testing ;) Old paradigms (edit near the "end," whatever that is) are still in the house.

**Comment by Carotejada** [comment]
Hi! I liked very much the activities; as said, you are a Curriculum Monster Chad :)

This is feedback only for "How we use the web" 

Preparation: I started to read and it says “do the activity on your own”, then I clicked on the link but I didn’t know what to do there. To me it is not clear what do we mean when we say activity. Is specifically the remixing part on Thimble? Because I understood these “How we use the web” as a complete project that has 6 activities. It would be good if we homogenize the concepts.  What is an activity, what is a project, or a session. 

Maybe for people that are familiarized with Mozilla curriculum  it is clear and obvious, but for those who are getting here for first time (like me) is not.  
﻿
What do you think if we use a graphic with the whole picture of the project at the beginning. This helps to start reading the content with a clear idea of what you need to achieve, and how each activity interacts with others. Sometimes when you start reading instructions you experience this anxiety for not having the complete clear idea, and you need to read again to connect -this happens to me frequently because I have no patience and I want to understand everything in one minute :( 

https://drive.google.com/open?id=0BxN5635WjvALWlJYd1FiRURFcnc

I also found this resource that could be interesting to include.  It is a counter of Internet users and it gives you an idea of the vertiginous growth http://www.internetlivestats.com/

**Comment by chadsansing** [comment]
Thanks, @Carotejada  - great ideas. I will send the 'time-bar' picture to design and see if it fits into the template under development.

We know there is a lot of text in most activities right now and that pages are very long, vertically. The new template should chunk information into smaller parts and present information more horizontally on the screen. We hope this will help people make clearer sense of each step.

I like the Web stats share and will look for a spot for it.

Our team should have a conversation soon - maybe after MozFest - to talk terms. Right now "Activity" means educator-facing lesson plan, "project" means Thimble webpage, and "tutorial" means the learner-facing steps inside Thimble.

I've added a few steps under each "Do the activity" prompt to clarify what that means. Let me know how it tests, peeps.

**Comment by chadsansing** [comment]
In production.
