### ISSUE TITLE
[Meta] Rio Mozilla Club Report 2014-2015

### ISSUE THREAD

**Issue by amirad** [mozilla/learning-networks#299]
A report encompassing all that happened with the Rio Mozilla Club's in the last year - including why we created them, what happened at them, what we learned and our suggestions for the project moving forward. 

http://workopen.org/rio2

**Comment by soapdog** [comment]
# Rio Mozilla Club Report 2014-2015 (_structure_)

Google doc for the report: All documents combined into https://docs.google.com/a/mozilla.com/document/d/1y5rsQ9lkCyvyg6Lb0BzyYxv4dzJnUf2UKHrcf2bLMRM/edit?usp=sharing

> This is the combined version of other previous documents.

## Introduction #300

What is this report about. Why it exists. Why it is important  

## Brazil, The Web & The Economic Crisis #301

How the economic changes affected the LAN House business? What about the pressure from Zero Rating and similar carrier subsidies? In this section we expand on what changed since 2014 and it affected the LAN House business. 

## What We Set Out To Do #302

The transition from an appmaker based project into a web literacy project and then leadership development. The creation of the world wide Mozilla Clubs program. How we adapted the program to the Rio context. List the objectives 

## What we did and what happened #303

What happened, what activities did we do, how often where sessions. Insert Rio case case

Google Doc: https://docs.google.com/a/mozilla.com/document/d/171unhxKDDie_YMsxTaiYLkU9v9UKZIILWegAZkCmuS0/edit?usp=sharing

## How The Venues Changed #305

What happened to the venues originally visited by our team? How  their users changed after our initial report?  

Even though we'll focus on the participating LAN Houses we need  to explain what happened to the other LAN Houses as well. At least what  happened to the other LAN Houses that were recommended by the initial  report (1 closed down, 1 never answered back, 1 had personal/private  health problems and decided not to pursue the project)  

We'll interview LAN House owners, employees and clients again. As  a new section, we'll interview our staff and volunteers.

Google Doc for the Interviews: https://docs.google.com/a/mozilla.com/document/d/1UvWQWc40HKsjLauMpybVP5gEZHzuL8afaN8EJe39DjY/edit?usp=sharing

Google Doc for how the venues changed: https://docs.google.com/a/mozilla.com/document/d/1VCSs4XSYaRDRA8ySB7iUQBc2W344WPvcLLK5RKWwnow/edit?usp=sharing

## What We Learned #306

Explain what we learned during this year. What didn't work, what worked well and from that what lessons we took. Its important to highlight what worked well and how we adapted our work to the reality of our venues and public. We came into the project with some per-conceptions on how it should work and some of them were not true.  What worked, what didn't 

Google doc: https://docs.google.com/a/mozilla.com/document/d/1DPWZ8HfD5Ano20KcNSH1jLTTat8srmEmQ129q3s8qfw/edit?usp=sharing

## Recommendations #307
- All based on what we've learned
- Legal Presence  
- Diversity programs  
- More people/staff (internships, fellowship, paid facilitators)  
- No exclusivity to LAN Houses, be able to seed clubs and/or events in venues from different nature such as museums, libraries.  
- Activities focused on engaging and sustaining volunteers as well.  
- Potentially expand into two new states (or large cities) (potentially São Paulo and one from the Northeast)  
  Google Doc: https://docs.google.com/a/mozilla.com/document/d/1ioKgA9MXnn7PJWuGPm4UqcK2B8Lucru1m0IVz2SC4Lg/edit?usp=sharing

## Summary #308

## Acknowledgements #308

**Comment by soapdog** [comment]
CC @benrito

**Comment by soapdog** [comment]
On Friday 28th we'll start placing the content online for revision using Google Docs. Besides sharing it with @amirad and @Carotejada, who else should we share it with?

**Comment by amirad** [comment]
I think you mean the 29th @soapdog! Feel free to share it here and I'll tag others who might be able to help.

**Comment by soapdog** [comment]
Added the first three chapters of the report. The docs are visible to anyone at Mozilla and can also be commented. Looking forward to feedback and tweaks.

More chapters following shortly.

**Comment by soapdog** [comment]
More chapters posted.

**Comment by amirad** [comment]
Thanks @soapdog 

@benrito @chrislarry33 @metaphorista @KalpanaSimhan the report is ready for some eyeballs! Scroll up to the Report Structure in this ticket and click the Google doc links below each header. Comments/edits can go directly into documents. 

Also @soapdog and I have been working on the narrative of why we spent less than we predicted - narrative can be seen at the bottom (allllll the way down) in this pad http://workopen.org/rio2 and Ruzanna and @KalpanaSimhan and I met last week to review budgeting and that narrative.

**Comment by soapdog** [comment]
All documents combined into https://docs.google.com/a/mozilla.com/document/d/1y5rsQ9lkCyvyg6Lb0BzyYxv4dzJnUf2UKHrcf2bLMRM/edit?usp=sharing

@KalpanaSimhan and @amirad, I am moving the issues and changes into this single document.

**Comment by soapdog** [comment]
Added tentative introduction section to the document.

**Comment by amirad** [comment]
This is done so closing!
