### ISSUE TITLE
[Community Engagement] Launch Mozilla Curriculum Workshop webcast

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#330]
- [x] Plan first workshop curriculum episode with co-host @amirad and producer Paul Oh.
- [x] Recruit guests for the first episode.
- [x] [Work with @kgorr on YouTube channel](https://github.com/mozilla/learning-networks/issues/327).
- [x] Work with @hannahkane on landing page.
- [x] File a design brief (not P1) for title and credits tiles and (maybe) badges/digital stickers for participants.

cc @ldecoursy 

[Back to issues.](https://github.com/mozilla/learning-networks/issues)

**Comment by chadsansing** [comment]
Welcoming @ohnopauloh to the mix as producer.

**Comment by KGorr** [comment]
Google Hangouts on Air Testing:

These two articles will walk you through everything:

Hangouts on Air How To (Including system requirements): https://support.google.com/plus/answer/2553119?hl=en

Hangouts on Air FAQ (MUST READ - lots of good 'what if Qs' for during the broadcast): https://support.google.com/plus/answer/2459411?hl=en&ref_topic=2553242

I followed everything step-by-step and didn't run into problems until I received this error message when I hit begin broadcast
![screen shot 2016-02-01 at 8 16 18 pm](https://cloud.githubusercontent.com/assets/14793388/12751985/0ad5a45a-c975-11e5-85ab-d1e1fdcf4542.png)

**Comment by amirad** [comment]
Strange error but thanks for the links @KGorr

**Comment by KGorr** [comment]
If the landing page doesn't happen before our 1st workshop, here are the links I found to help embed the hangout & etherpad into WordPress:

Etherpad embedding: https://github.com/ether/etherpad-lite/wiki/Embed-Parameters
- Insanely easy. Tested it and works with flying colors.

Google Hangouts embedding: https://managewp.com/embed-live-google-plus-hangout-wordpress
- Not as easy, but can't test since I have the error mentioned above when trying to get a hangout on air to work.

If we do this on Wordpress, how much traffic can it handle before it starts crashing?

**Comment by jgmac1106** [comment]
@KGorr @Amirad I see that error in schools that have disabled HoA and
Google+. I wonder if the Google Apps for Business Mozilla uses is set to
the same settings.

**Comment by ldecoursy** [comment]
Launched! :icecream: Can we close? @chadsansing

**Comment by chadsansing** [comment]
Definitely. Kudos, team!
