### ISSUE TITLE
Design template for Club guides

### ISSUE THREAD

**Issue by hannahkane** [mozilla/learning-networks#332]
We've identified the [After School Clubs guide](https://docs.google.com/document/d/1rUivWQybJymNlfZZHWkSJqFN5TNDVuPRSH_YCObALeM/edit) as an exemplary piece of content, so we'll start with that.

Will create pages in this repo.

Design assets include:
- [Mozilla Clubs wordmark](https://d157rqmxrxj6ey.cloudfront.net/mozillalearning/17695/)
- photos [to be provided by @amirad]
- another variation on the fox? [ideas for clothing/props from @amirad @Carotejada]

cc @flukeout

**Comment by amirad** [comment]
@flukeout you can grab pictures from this blog http://riomozillaclub.org/ (scroll down) or these https://www.flickr.com/photos/leaomozillaclub/

**Comment by amirad** [comment]
Club fox makes me think of teacher-ish fox. So has glasses, either a book or mobile, some sort of activity/game/teaching kit in hand and any other educator type things. Club fox might even have many small clubbers with them!

**Comment by Carotejada** [comment]
Agree with Amira. Would add that clubbers tend to be a bit rebellious...
and "out of system" prototype. That's why I like this graphic used in
Mozlando:

![fox_club](https://cloud.githubusercontent.com/assets/14875631/12785718/db1c5a50-ca5b-11e5-9f18-606b5fd91efa.png)

​

On Tue, Feb 2, 2016 at 5:09 PM, Amira notifications@github.com wrote:

> Club fox makes me think of teacher-ish fox. So has glasses, either a book
> or mobile, some sort of activity/game/teaching kit in hand and any other
> educator type things. Club fox might even have many small clubbers with
> them!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mozilla/learning-networks/issues/332#issuecomment-178853864
> .

## 

Carolina Tejada
Atlas Corps Fellow
Mozilla Foundation

**Comment by amirad** [comment]
The fab @chadsansing hacked @flukeout's earlier template for an activity. Wanted to share it here in case it's helpful https://d157rqmxrxj6ey.cloudfront.net/chadsansing/29663/#overview

**Comment by amirad** [comment]
Also, instead of a club's fox thought an education fox would make more sense and threw it out to the team to see what they thought an education fox would look like. Here's what we thought:

```
Andre: Education fox need makers, post-it notes, flip chart, smartphone, books, glass and a tuna sandwich.
 Amira: Education fox has glasses, either a book or mobile in hand and some sort of activity/game +1 /teaching kit in the other hand
 Chad: tablet or laptop, game, 'school-spirit'-like hoodie, great shoes, a book, backpack+1 to the backpack!? maybe this is a learning fox? learning fox IS education fox+1; maybe a hinking cap, too?
learning is less formal and more inclusive than education, i think, connotatively
 Lainie: brain full of things - robot, book, code, other people (foxes)
 Kristina: Balancing a stack of books or maker type things and wearing a monocle! +1 for balancing act! and perhaps a bowtie or something else fancy
 Hana: backpack, books, sneakers!
 Katie: apple, backpack, tablet and books under the arm
MM: struggling with this so that it's not gender specific but inviting to girls, youth broadly.   +1+1Soemthign that speaks to collaboration, making, play -- not just "school" learning please, and not US centric+1
Lindsey: backpack, headphones, something makery, 
An-Me:smartphone/tablet/laptop, headphones, backpack, VAN sneakers, gender neutral
Sarah- Tablet in hand, with html code visable or a Rosetta stone like tablet, backpack
Janice: definitely a smartphone/tablet, headphones would be nice, and a fun lunchbox +1 
Julia: backpack, headphones, snack pack, pencil case, notebook, 
ErikaD: Google image search has strong feelings about this. Education Fox must be wearing a graduation cap and standing beside a globe and a stack of books. Teacher Fox must be standing at a chalkboard at a 45 degree angle, smiling at us while wearing a white shirt or sweater set.
Chris: saddlebag, hipster school uniform, School of Rock style: https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=0ahUKEwi5svbr_NvKAhXMdD4KHfVWDyQQjRwIBw&url=http%3A%2F%2Fwww.nydailynews.com%2Fentertainment%2Fhollywood-uniform-gallery-1.85100%3FpmSlide%3D1.90323&psig=AFQjCNFx21qRUBusAh9Jq9U-HJA4iZlxNw&ust=1454601996105519
```

Also at the top of the pad if that is easier to digest: https://public.etherpad-mozilla.org/p/edhubteamcall_jan16

**Comment by chadsansing** [comment]
#allthefox; how do people feel about 'Learning Fox' - 'education' sometimes seems more formal, less inclusive, more 'done to someone,' maybe?

**Comment by Carotejada** [comment]
Would like to share a comment that a community member sent to me about the Clubber's identity:

"During the Whistler work week, I remember a conversation in which we were focusing on Club captains as facilitator or more of a logistics person, who makes sure things are set up to ensure the smooth running of the learning process in clubs rather than a being a teacher. This means that he/she can be interested in organizing things, but is it's not necessary that he/she needs to be the teacher".

I'm not sure if our clubbers identify themselves as pure educators.

**Comment by chadsansing** [comment]
Nice share, @Carotejada. I think the cross-Mozilla curriculum work will unpack a lot of thinking about common ground between our community members' roles.

**Comment by flukeout** [comment]
@Carotejada @amirad Here's a first pass at converting the After School Clubs Guide into the template:

**http://flukeout.github.io/master-template/clubs/**

**Note**: none of the links in the content work yet.

Let me know your thoughts so far. I used an image I found on the Rio clubs site. We can work on a fox a bit later.

**Comment by Carotejada** [comment]
@flukeout I think the template (style and navigation) works well. 

PSD: I really want the fox :(

**Comment by flukeout** [comment]
**Update**
I made it so that the template is generated from Markdown, see here:
- Live Template - http://flukeout.github.io/master-template/clubs-markdown/#introduction
- Markdown Source - https://github.com/flukeout/master-template/blob/master/clubs-markdown/content.md

To edit the template, you edit the markdown file without having to worry about the HTML syntax at all. The left-side navigation is generated based on the top-level headings used in the content.md file.

cc @amirad @Carotejada

**Comment by Carotejada** [comment]
Oh, that's great @flukeout

**Comment by amirad** [comment]
It looks great @flukeout - simple and perfect. 

I'm curious if we should have a more generic picture in the template?! We know that picture is from a club but there isn't any way that others will know. What do you think about using one of the illustration designs that Sabrina has mapped out for the teach style guide: https://redpen.io/ywb006488f91162838 The first and last circle (in the illustration section) look super clubby to me. 

Also when I click on the link the science logo is in the tab description?!?

And I know this a noob question but it would be pretty easy for someone like myself to replicate and fill in this template multiple times right? The markdown part seems pretty great!

**Comment by flukeout** [comment]
@amirad Yeah - the picture I picked is just a placeholder, will experiment with some of the imagery from the redpen you linked.

I'll fix the favicon in the tab, it's still using it because I adapted the science template.

Yeah, if you follow the general structure of the markdown file, it will auto-generate this no problem. I'll set it up you can try it sometime next week.

**Comment by amirad** [comment]
Purrrrfect @flukeout 

You. Are. Great.

**Comment by soapdog** [comment]
hey @flukeout,

This is looking awesome!!! I _loved_ it!!!

I've been playing with the `clubs-markdown` template and notice a potential difficulty with the sidebar. In some of our guides we have lots of items in our table of content, since the sidebar position is fixed, we end up with items that are below the visible part of the page and unreachable.

![example of out of reach content](http://andregarzia.com/shots/Mozilla_Club_Guide_Mixing_Your_Afterschool_Program__Your_Mozilla_Club_2016-02-10_13-36-31.png)

I am not sure what would be the best solution there...

**Comment by flukeout** [comment]
Thanks for pointing that out @soapdog - one solution that I've been trying is to remove the sidebar image when you move beyond the first section, as seen here...

http://flukeout.github.io/master-template/teach/#overview

We could do something similar as soon as someone scrolls down to or clicks on another section. That would free up some room - but still wouldn't account for navigations with many items.

One idea for your particular problem is to shorten the labels of the navigation, for example...

`I.B. Do an interview with a Regional Coordinator to complete your pledge` could be shortened to just `2) Interview a Regional Coordinator` - shorter labels work better for navigation elements.

Cheers!

**Comment by amirad** [comment]
@flukeout is https://github.com/mozilla/learning-networks/issues/332 final? Want to start dropping content into it asap. 
@hannahkane do you think you can take @KGorr and I through a tutorial on how to use markdown and make multiple guides at lightening speed next week?

**Comment by hannahkane** [comment]
@amirad - yes def to the tutorial, plus we're going to prioritize getting these new templates into a CMS, which would make creating/updating these a lot like editing a page or blog entry on Wordpress - no html, no markdown, just a basic wysiwyg editor ("what you see is what you get" - like when there's a "B" button that means "bold").

**Comment by amirad** [comment]
That sounds wonderful @hannahkane - what's timeline on that? We need to transfer links to share on guides in a week or so?

**Comment by flukeout** [comment]
@amirad I'm getting everything ready for you to be able to do this - it will be ready tomorrow when you are all back.

**Comment by amirad** [comment]
Mucho gracias @flukeout!!!!

**Comment by flukeout** [comment]
No problem @amirad - I just pushed some changes to that repo with the new content and [instructions](https://github.com/mozilla/learning-networks/blob/gh-pages/README.md) on how to use the template.

Let me know if you have questions - happy to take some time tomorrow to walk both of you through it and identify problems and opportunities for improvements.

**Comment by Carotejada** [comment]
@flukeout @hannahkane this is great. Will play with it and let you know how it goes :+1:  :smile: :da

**Comment by amirad** [comment]
THANK YOU SO MUCH @flukeout 

One last thing before closing out this ticket! I'm having the same trouble that Andre is having up above with the navigation getting lost below the fold. Do you think theirs any possibility of increasing the sidebar a bit to allow for more text? Or increasing the text space in the sidebar? My titles aren't long but fold over quickly when more than two words. http://mozilla.github.io/learning-networks/clubs/events-women-girls-guide/

**Comment by flukeout** [comment]
Cool no problem - okay, I've filed an issue to address this and will update the CSS shortly.

**Comment by flukeout** [comment]
Filed in #346
