### ISSUE TITLE
Figure out localization process for Club Guides

### ISSUE THREAD

**Issue by hannahkane** [mozilla/learning-networks#335]
Now that the template and authoring process is [well underway](https://github.com/mozilla/learning-networks/issues/332#issuecomment-180551688), perhaps we should think about a translation or localization workflow.

@amirad @Carotejada - once you've had a chance to play around with @flukeout's markdown -> html template, let's talk through what a localization flow might look like.

**Comment by hannahkane** [comment]
cc @soapdog

**Comment by flukeout** [comment]
@hannahkane I haven't yet given @amirad and @Carotejada a way to try out the template for themselves. Will do that soon we can continue evaluating.

**Comment by soapdog** [comment]
@hannahkane,

I've been thinking a lot about this and I am coming to a conclusion that maybe our current solutions in the form of pontoon/pottle/transifex are not the best ones. Most of these tools are focused on translating HTML interfaces where each contributor is localizing a small piece of text that fits inside a tag.

In our case we have larger structured texts in the form of markdown files. Markdown is easy to write and tweak but it is not something that those translation platforms can work with. I am beginning to think that our markdown "back-end" works fine, what we have is an interface problem where dealing with github and issues poses some friction for volunteers. If we had a web interface that allowed them to visualize the markdown files and translate them with a commit being generated in the back-end we might end up with a more friendly solution.

What do you think?

**Comment by hannahkane** [comment]
@soapdog - this is a useful description of the problem. Are you suggesting we build the web interface? Would we be essentially building a new piece of translation software?

**Comment by amirad** [comment]
@soapdog you have an update here right?

**Comment by ldecoursy** [comment]
Ping @soapdog

**Comment by soapdog** [comment]
Sorry for my lapsing on these issues. I have an update here. Posting it right now.

Our L10N campaign worked pretty well for us. The workflow with github issues worked great for us since it allowed for very fine tuned control over the translations but it posed some friction for our volunteers who were not used to github and would prefer a web interface.

Since the last months I've taken a good look at the tools at our disposal, mostly Pontoon, to check how well suited they'd be for our guides and activity work. I have the feeling that Pontoon is not suitable for our guides work without a lot of reworking because of the following reasons:
- We're using static pages without a back-end.
- We're using markdown for content
- We're falling in love with github issues

To make Pontoon work with all those items above would probably require a lot of work. Pontoon is specially good to translate websites by attaching L10N information directly to the HTML nodes. It is not really suited for our Markdown workflow.

I had a feeling here that there was a way to keep our "github issue" based L10N workflow while still providing a friendly web interface to volunteers. I have built a proof-of-concept editor that is usable right now for our purposes. There is a [gif animation file showing it working](http://andregarzia.com/images/l10n.gif):

![gif animation file showing it working](http://andregarzia.com/images/l10n.gif)

This is a self-contained client-side webapp that can work with any of our guides. I should clean the source code though, I built this too quickly. The code is [available on the 'enchancement-l10n-support' branch of this repo](https://github.com/mozilla/mozilla-club-guides/tree/enhancement-l10n-support).

Again sorry for the delay.

**Comment by soapdog** [comment]
So far, I've only shown this editor to @amirad, I would love to have feedback, impressions, from @ldecoursy and @hannahkane.

**Comment by ldecoursy** [comment]
This looks cool @soapdog. Would the workflow be similar to how we ran the l10n campaign for Web Lit Basics I?

**Comment by soapdog** [comment]
@ldecoursy for us it would be the same. Each new translation becomes a new issue which we check and move to new markdown files when approved. It is a bit easier since these new issues are already tagged with L10N and clubs so our notifications and filtering become more friendly. For the volunteers this is a lot more friendly since they don't need to deal with github besides having an account. The little web interface handles all the issue creation for them.

**Comment by hannahkane** [comment]
Wow, @soapdog, this is amazing. Genius. :)

My concern with the workflow is that the translator won't be able to see a preview of their work, which seems important since they'll be working with markdown. 

Is the final step one of our staff members taking the translated copy and publishing a version of the content (putting it in the appropriate folder, as described in #333)?

cc @flukeout - curious to know your thoughts about the workflow described above

**Comment by soapdog** [comment]
@hannahkane 

```
My concern with the workflow is that the translator won't be able to see a preview of their work, which seems important since they'll be working with markdown.
```

We can add a preview feature easily, the code is already there but I haven't added a button. A little toggle that switches from preview to edit.

```
Is the final step one of our staff members taking the translated copy and publishing a version of the content (putting it in the appropriate folder, as described in #333)?
```

Yes, that is the final step and if there is any extra exchange of information needed between staff and volunteer, they will be able to use that issue for it so this approach makes very easy to interact beyond simply accepting translations.

@flukeout sorry for the poor design on my little PoC, I just wanted to check if I could actually make this workflow work :-P
