### ISSUE TITLE
[Testing] [Intermediate Web Lit II] Buttons and Alerts

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#380]
Help test this new storytelling-with-scripts activity!

Lesson plan: http://chadsansing.github.io/curriculum-testing/intermediate-web-lit-two/session01-buttons-and-alerts.html#overview
Thimble Project: https://thimbleprojects.org/chadsansing/50661

Looking for help with copy editing, broken links and images, and other bugs here on GitHub.

Looking for feedback on content, difficulty, and tutorials [over on Discourse](https://discourse.webmaker.org/t/testing-intermediate-web-lit-ii-buttons-alerts/759).

Testing closes on 4/29/16.

[Back to issues.](https://github.com/mozilla/learning-networks/issues)

**Comment by KGorr** [comment]
**Lesson Plan:**
• Intro - There is a lone “Write the web” subheader at the top with no content beneath
• #1 Preparation 
    o   typo “looks” should be “look”
    o   the Thimble link has a typo
• #2 Building Human Machines – may be useful to link to a Human machine example online. It is a hard one to describe in words!
    o   “a styling instructions” should not have the “a”
    o   last sentence is 1st paragraph seems runon-ish
    o   #5 can drop the “that does something.”
    o   #6 – it might be more clear for “Parts of the machine” to say “Group members”
    o   #11 & #12 – instead of “performs” it may be more clear to use “mimics”
    o   sentence introducing the last set of bullets has a typo “faciliutate”
• #3 Discovering JavaScript
    o   1st sentence typo “intructions”
    o   2nd paragraph, 2nd sentence typo “heppen”
    o   2nd paragraph, 3rd sentence typo “Foer”
    o   Suggested rewrite for: “Functions can use values attached to variables, as well as change those values.” Is “Functions can use values attached to variables, and can change those values.”
    o   Omit “so” from intro video sentence
• #4 Coding a Button & Alert
    o   Remove “all” from 1st sentence and change “the button the page” to “the button on the page”
    o   7th paragraph typo “parentehses”
• #5 Reflection
    o   1st bullet typo: “descrtibe”
    o   6th bullet typo: “ther”

**Thimble Project:**

“For example, if we wrote a function to describe a cat that expected certain characteritics like eye color or hair color, we could use variables and their values to describe or list the parts that make the whole.”
• This paragraph has a typo “characteritics” and is also very confusing. Is the cat expected to have certain characteristics, or the function?’ ☺
• #3 Alert 4th “paragraph” has a typo “vairable”
• #4 Javascript 3rd “paragraph” typo “button a function” should be “button to a function”
• #5 change the story: 4th “paragraph” : “be sure to use single quotation marks are inside the story and which contain the story as a string.”  There is something missing here but I’m not sure what it is.
    o   The last paragraph in this section is missing a step I think. You need to click on the index.html and then click on the preview pane to test it, yes? The preview pane instructions are missing.
• #7 mess with code – 2nd paragraph typo “thos”
• #8 credit yo’self – 1st paragraph typo “sytling”
• Ending paragraph should be “connection” instead of “connected”

**Comment by chadsansing** [comment]
Great - thank you, @KGorr!

**Comment by chadsansing** [comment]
The curriculum template might get a light overhaul soon to improve readability. In the meantime, please ship me any addition feedback here or via email.
