### ISSUE TITLE
Adding sequencing to activities on web literacy page

### ISSUE THREAD

**Issue by jgmac1106** [mozilla/learning-networks#392]
Now that the map (the React circle is sooo cool) serves up activities I am wondering if we should put a sequence on them.

So If I am on share the first thing served up is web chef. If you click on it you see that it is section three but have no context to the section of "what" nor navigational options back to section two and four. 

So I am thinking spaced equally with the activity level and the time would be (Activity 3 of 6 in Web Lit I), hyperlinked possibly.

The headers on the activity pages (web chef) also need to change or need more context.

**Comment by ldecoursy** [comment]
There's this ticket which may be related: https://github.com/mozilla/teach.mozilla.org/issues/1655 cc @chadsansing @hannahkane who may have more info.

**Comment by hannahkane** [comment]
Thanks for raising this @jgmac1106.

https://github.com/mozilla/teach.mozilla.org/issues/1655 is related but wouldn't solve this because it's about creating navigation for within a single activity (imagine, for example, "next" buttons at the bottom of each screen within [this activity](https://chadsansing.github.io/curriculum-testing/curriculum-migration/web-lit-basics-two-migrated/session01-why-do-we-use-the-web.html#overview), so that you don't have to use the side nav).

What I think Greg is bringing up here is about the sequencing of activities within a unit. I'd defer to @chadsansing with regard to whether we want to do that or not. Do we think it's important that activities be sequenced in a certain way? If so, I'd like to work on a solution within the newer template, rather than the old ones which we're still using for Web Lit Basics 1 (largely because we don't have a localization solution for the newer templates yet).

**Comment by chadsansing** [comment]
@hannahkane, for the most part, activities are sequenced, but implicitly rather than explicitly. A simple solution might be to number the title of each activity under its unit header, like so:

> Web Lit Basics II
> 1. Why do we use the Web?

We could also add a line item to the overview. Thoughts, @ldecoursy, @jgmac1106, @anmechung?

**Comment by hannahkane** [comment]
I think we probably need to add context to the module itself. So, for example, on [this page](https://chadsansing.github.io/curriculum-testing/curriculum-migration/web-lit-basics-two-migrated/session01-why-do-we-use-the-web.html#overview) we need to say something like "Part 1 of 9" and link back to [this page](https://teach.mozilla.org/activities/web-lit-basics-two/). Does that make sense?

**Comment by anmechung** [comment]
@chadsansing @hannahkane Seems like we might need both? number the title of each activity under its unit header to make it explicity, and also add context to module itself. @jgmac1106 - would this do it?

**Comment by jgmac1106** [comment]
That sounds like a plan.

**Comment by hannahkane** [comment]
Thanks to whomever added "Activity X of Y" to the modules themselves! 

Looking at it, I'm realizing it's perhaps slightly confusing to have that phrase link back to the index directly. Maybe it should say "Activity X of Y" (unlinked) with arrows to "next" and "previous" and then a smaller bit of text that reads "View all activities in this unit" or something like that.

**Comment by chadsansing** [comment]
Not sure what to do next. We should test somehow. I think it might be confusing or distracting to see nav pointing you away from the activity at the top of the activity (so un-linking is probably good). There is a link to the next activity at the end of each reflection and assessment section, but that's pretty buried.

**Comment by jgmac1106** [comment]
Maybe it isn't a link on the weblit page just say Activity X of Y. Then you
can make the navigation options on the activity pages itself.

**Comment by chadsansing** [comment]
I'll leave the sequencing info, but remove the link for now.

**Comment by hannahkane** [comment]
Is the design work @flukeout is doing right now in https://github.com/mozilla/teach.mozilla.org/issues/1841 addressing this issue? Seems to me it is.

**Comment by jgmac1106** [comment]
Closing since its a dupe then.
