### ISSUE TITLE
Priorities for L10N work related to Portuguese

### ISSUE THREAD

**Issue by soapdog** [mozilla/learning-networks#398]
## Context

The lack of localized material is preventing some powerful partnerships in Brazil. We can't partner with educational departments or the government until we have such material available in the local language. This is probably affecting other countries as well and we know that a solution for L10N will be put in place eventualy. This bug serves as a list of priorities of what needs to be localized and is written from our Brazilian perspective, other countries might have different priorities.
## The Learning Site

The number one priority for L10N should be the http://learning.mozilla.org website. The reasoning behind this is that the decision makers from the departments that we want to partner with will learn about our project from this page. As our main public channel to promote our programs, this website is our primary point of contact with people who are unaware but curious about  us. Not only our textual content must be localized but also all the "application process" to become a Club Captain. 

Public officials, educational departments, universities, all of them will value a comprehensive set of information about our programs in local language. This website is what will enable us to take further steps after approaching these potential new partners.
## The activities

After the website is localized, the second priority is the activities themselves. The website will get people into our program but its the activities who will provide them with the educational resources they will apply with their learners. Without those resources being made available in Portuguese, the new captains and facilitators will have a hard time coming up with events.
## Guides

Many of the guides can be replaced with chats with Regional Coordinators and thats why they are in the third place in this priority list. While they are very useful, the other resources are more important in our view.

**Comment by soapdog** [comment]
cc: @amirad @hannahkane

**Comment by soapdog** [comment]
cc @rodrigopadula

**Comment by anmechung** [comment]
Translation of Web Literacy map has come up lately as well, and I understand that translation in the past has been via volunteers.  Given this and the resources @soapdog outlines above seem to be greater demand and localization seems to be a priority, and will help us reach more people faster and more efficiently, should some kind of financial help be considered for getting translations done sooner? @chrislarry33

**Comment by hannahkane** [comment]
Thanks for this ticket, @soapdog. 

Can we be more specific about what it means to localize learning.mozilla.org? Specially, should that include:
- email updates (opportunity to sign up on the homepage and the community page)
- the blog (embedded on homepage)
- promotional banners (currently "Encrypt")
- links to external content in English (e.g. Twitter, Discourse, Goggles, Webmaker, MozFest) (perhaps the content on Learning should be localized, but with a warning that the linked content is English only?)
- Community Call and Curriculum Workshop conte

I realize this ticket is specifically about pt-BR, but I'm wondering about the Club Captain application form more broadly. I wonder if we should only localize the form into locales that we can support with staff/volunteers, since that interaction implies there will be follow-up/ongoing communication in the same language.

Just a note about why I'm asking these questions. I'm not asking because it's "harder" to localize more content. Once we do the necessary technical groundwork for content on the Learning site, localizing more content is only as difficult as it is to find awesome people willing to do the localization work (exceptions to this would be emails, blogs, and promo banners, which would all need to be localized with different processes). I'm asking because I want to work to have a general policy/plan for l10n that reflects our ability to provide multi-lingual support.

**Comment by Carotejada** [comment]
@anmechung [this](https://docs.google.com/document/d/15CJ0Tt6muh1zZPRYbqb_GXIL48MNjRvO__A54BQ8qZ0/edit?usp=sharing) is the Web Lit map translated into Spanish.  We still need to have a discussion about concepts that are hard to translate (or that I just didn't understand 🎯 

@hannahkane  I guess we can keep localizing a few basic resources so we are ready to publish them once the technical issues are solved.
